pub const PROTOCOL_VERSION = "0";
pub const PROTOCOL_PREFIX = "jamnp-s";
pub const CONNECTION_TIMEOUT_MS = 5000;

// UP Streams
pub const UP_STREAM_BLOCK_ANNOUNCEMENT: u8 = 0;

// CE Streams
pub const CE_STREAM_BLOCK_REQUEST: u8 = 128;
pub const CE_STREAM_STATE_REQUEST: u8 = 129;
pub const CE_STREAM_SAFROLE_TICKET_TO_PROXY: u8 = 131;
pub const CE_STREAM_SAFROLE_TICKET_DISTRIBUTION: u8 = 132;
pub const CE_STREAM_WORK_PACKAGE_SUBMISSION: u8 = 133;
pub const CE_STREAM_WORK_PACKAGE_SHARING: u8 = 134;
pub const CE_STREAM_WORK_REPORT_DISTRIBUTION: u8 = 135;
pub const CE_STREAM_WORK_REPORT_REQUEST: u8 = 136;
pub const CE_STREAM_SHARD_DISTRIBUTION: u8 = 137;
pub const CE_STREAM_AUDIT_SHARD_REQUEST: u8 = 138;
pub const CE_STREAM_SEGMENT_SHARD_REQUEST: u8 = 139;
pub const CE_STREAM_SEGMENT_SHARD_REQUEST_WITH_JUSTIFICATION: u8 = 140;
pub const CE_STREAM_ASSURANCE_DISTRIBUTION: u8 = 141;
pub const CE_STREAM_PREIMAGE_ANNOUNCEMENT: u8 = 142;
pub const CE_STREAM_PREIMAGE_REQUEST: u8 = 143;
pub const CE_STREAM_AUDIT_ANNOUNCEMENT: u8 = 144;
pub const CE_STREAM_JUDGMENT_PUBLICATION: u8 = 145;
