const Instruction = @import("../instruction.zig").Instruction;

pub const ArgumentType = enum {
    no_arguments,
    one_immediate,
    one_offset,
    one_register_one_immediate,
    one_register_one_immediate_one_offset,
    one_register_two_immediates,
    three_registers,
    two_immediates,
    two_registers,
    two_registers_one_immediate,
    two_registers_one_offset,
    two_registers_two_immediates,

    pub fn lookup(instruction: Instruction) ArgumentType {
        return lookupArgumentType(instruction);
    }
};

pub fn lookupArgumentType(instruction: Instruction) ArgumentType {
    return switch (instruction) {
        .trap, .fallthrough => .no_arguments,
        .ecalli => .one_immediate,
        .store_imm_u8,
        .store_imm_u16,
        .store_imm_u32,
        => .two_immediates,
        .jump => .one_offset,
        .jump_ind,
        .load_imm,
        .load_u8,
        .load_i8,
        .load_u16,
        .load_i16,
        .load_u32,
        .store_u8,
        .store_u16,
        .store_u32,
        => .one_register_one_immediate,
        .store_imm_ind_u8,
        .store_imm_ind_u16,
        .store_imm_ind_u32,
        => .one_register_two_immediates,
        .load_imm_jump,
        .branch_eq_imm,
        .branch_ne_imm,
        .branch_lt_u_imm,
        .branch_le_u_imm,
        .branch_ge_u_imm,
        .branch_gt_u_imm,
        .branch_lt_s_imm,
        .branch_le_s_imm,
        .branch_ge_s_imm,
        .branch_gt_s_imm,
        => .one_register_one_immediate_one_offset,
        .move_reg,
        .sbrk,
        => .two_registers,
        .store_ind_u8,
        .store_ind_u16,
        .store_ind_u32,
        .load_ind_u8,
        .load_ind_i8,
        .load_ind_u16,
        .load_ind_i16,
        .load_ind_u32,
        .add_imm,
        .and_imm,
        .xor_imm,
        .or_imm,
        .mul_imm,
        .mul_upper_s_s_imm,
        .mul_upper_u_u_imm,
        .set_lt_u_imm,
        .set_lt_s_imm,
        .shlo_l_imm,
        .shlo_r_imm,
        .shar_r_imm,
        .neg_add_imm,
        .set_gt_u_imm,
        .set_gt_s_imm,
        .shlo_l_imm_alt,
        .shlo_r_imm_alt,
        .shar_r_imm_alt,
        .cmov_iz_imm,
        .cmov_nz_imm,
        => .two_registers_one_immediate,
        .branch_eq,
        .branch_ne,
        .branch_lt_u,
        .branch_lt_s,
        .branch_ge_u,
        .branch_ge_s,
        => .two_registers_one_offset,
        .load_imm_jump_ind => .two_registers_two_immediates,
        .add,
        .sub,
        .@"and",
        .xor,
        .@"or",
        .mul,
        .mul_upper_s_s,
        .mul_upper_u_u,
        .mul_upper_s_u,
        .div_u,
        .div_s,
        .rem_u,
        .rem_s,
        .set_lt_u,
        .set_lt_s,
        .shlo_l,
        .shlo_r,
        .shar_r,
        .cmov_iz,
        .cmov_nz,
        => .three_registers,
    };
}
